// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.koma.backuprestore.data.source.backup;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class BackupDataSource_Factory implements Factory<BackupDataSource> {
  private final Provider<Context> contextProvider;

  public BackupDataSource_Factory(Provider<Context> contextProvider) {
    assert contextProvider != null;
    this.contextProvider = contextProvider;
  }

  @Override
  public BackupDataSource get() {
    return new BackupDataSource(contextProvider.get());
  }

  public static Factory<BackupDataSource> create(Provider<Context> contextProvider) {
    return new BackupDataSource_Factory(contextProvider);
  }
}
