// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.koma.backuprestore.data.source.restore;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class RestoreDataSource_Factory implements Factory<RestoreDataSource> {
  private final Provider<Context> contextProvider;

  public RestoreDataSource_Factory(Provider<Context> contextProvider) {
    assert contextProvider != null;
    this.contextProvider = contextProvider;
  }

  @Override
  public RestoreDataSource get() {
    return new RestoreDataSource(contextProvider.get());
  }

  public static Factory<RestoreDataSource> create(Provider<Context> contextProvider) {
    return new RestoreDataSource_Factory(contextProvider);
  }
}
